### ISSUE TITLE
Setup IoT Edge Simulator failed

### ISSUE THREAD

**Issue by yalaas** [microsoft/vscode-azure-iot-edge#574] opened 2021-04-08 19:25 UTC
- VSCode Version: 1.55.0
- OS Version: Ubuntu 16.04 (container)
- Extension Version: 1.23.0

Steps to Reproduce:

1. Install Python 3.5 on Ubuntu16.04 VSCode Remote Container
2. Install iotedgehubdev on Ubuntu 16.04 VSCode Remote Container 
2. Install Azure IoT Edge extension
3. Run "Azure IoT Edge: Setup IoT Edge Simulator" from VS Code command palette
4. Observe the error "Cannot execute command since 'iotedgehubdev' is not installed. Please install it first for IoT Edge Simulator.
Error: Please install 'iotedgehubdev' tool first for IoT Edge Simulator."

I confirmed "iotedgehubdev" is installed and can run from the terminal. 

**$ which iotedgehubdev**
_/usr/local/bin/iotedgehubdev_

**$ iotedgehubdev** 
_/usr/local/lib/python3.5/dist-packages/OpenSSL/crypto.py:14: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release of cryptography. Please upgrade your Python.
  from cryptography import utils, x509
Usage: iotedgehubdev [OPTIONS] COMMAND [ARGS]...

Options:
  --version   Show the version and exit.
  -h, --help  Show this message and exit.

Commands:
  generatedeviceca  Create IoT Edge device CA
  modulecred        Get the module credentials such as connection string and certificate file path.
  setup             Setup the IoT Edge Simulator.
  start             Start the IoT Edge Simulator.
  stop              Stop the IoT Edge Simulator.
  validateconfig    Determine whether config file is valid_

Does this issue occur when all other extensions are disabled?: No

**Comment by cindydeng1998** [comment] 2021-04-08 20:45
@yalaas Thank you for bringing this issue to our attention, we are aware of some issues regarding Python 3.5 support on the Edge simulator and are working on a fix. This is added to our backlog and we will let you know as soon as we have a solution.

**Comment by yalaas** [comment] 2021-04-09 14:23
@cindydeng1998 thank you for the quick response! I forced iotedgehubdev to be installed under Python 2.7 and that provided a workaround for issue. This further confirms the issue to be related to Python 3.5, or perhaps 3.x. Python 2.7 reached the end of its life on January 1st, 2020, a lot of packages dropped support for it already. In fact, I had to revert iotedgehubdev to v0.14.1 because of docker-compose version dependency.  Expediting the fix for this issue will be appreciated. 

For anyone who is running into this issue, here is a quick workaround:

_wget https://bootstrap.pypa.io/pip/2.7/get-pip.py 
python get-pip.py 
pip2.7 install iotedgehubdev==0.14.1_

**Comment by marianan** [comment] 2021-04-23 21:59
Hello @yalaas, I tried to reproduce the issue you are running into. There is no Ubuntu 16.0 remote devcontainer available any more (end of standard support [link](https://wiki.ubuntu.com/Releases), so I tried 18.04 instead. 
<img width="196" alt="UbuntuVersions" src="https://user-images.githubusercontent.com/10135329/115933291-6f2e4700-a443-11eb-99e5-daed3c5b80ac.png">

The iotedgehubdev install fails because Docker is not installed on the dev container image. This will cause issues for building the solution before it even gets to execute. I suggest running Docker on your local dev environment or on a VM and building/debugging/simulating Edge solutions there.

If your scenario requires remote execution, please share what are the specific constraints and we can help brainstorm ideas to get your project working.

**Comment by marianan** [comment] 2021-05-03 13:59
Closing the issue as no recent symptoms are reported.

**Closed by marianan** 2021-05-03 13:59 UTC
Labels: InBacklog
