### ISSUE TITLE
Tooling: instead of docker image repository, ask for login server instead

### ISSUE THREAD

**Issue by adashen** [microsoft/vscode-azure-iot-edge#180] opened 2018-06-25 05:20 UTC
Current instruction is removing "localhost:5000" with login server, not the entire string.  This is easy to miss.  Since "samplemodule" was defined in the previous step, this step should only ask for the login server and use the previous string as default.

**Comment by talmdal** [comment] 2018-09-19 16:20
+1 for this... I missed that entirely and it took me into a couple of wasted hours trying to get it right :-(

**Comment by konichi3** [comment] 2021-01-09 00:29
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:29 UTC
Labels: Obsolete, enhancement
