### ISSUE TITLE
validate the envs in deployment template when generate manifest

### ISSUE THREAD

**Issue by adashen** [microsoft/vscode-azure-iot-edge#173] opened 2018-06-21 14:29 UTC
Now we have set credentials in the .env file. When generate the final deployment manifest. It should check whether all the required environment variables have been expanded. If not error should be shown to user and ask set correct env.

**Comment by JMayrbaeurl** [comment] 2019-03-04 10:14
@formulahendry Any plans on working on this feature request? Would be really important to get this asap, because we need a way to store other credentials as well. And I would like to use other VS Code Env variables like the project file location, too.

**Comment by konichi3** [comment] 2021-01-09 00:28
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:28 UTC
Labels: Obsolete, feature request
