### ISSUE TITLE
module will repeat display in the Edge device after create twice deployment for single device

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#223] opened 2018-08-08 04:22 UTC
OS: ubuntu 17.04
toolkit:1.2.0
edge :1.2.0-rc

test steps:
1. create new C module solution 
2.Right-click the deployment.template.json file, and click Build and push  IoT Edge Solution
3.Right click on an Edge device in device tree, select Create deployment for Edge device 
4. Start Monitoring D2C message and debug code, then stop monitoring D2C message

5.create new Python module solution
6.Right-click the deployment.template.json file, and click Build and push  IoT Edge Solution
7.Right click on an Edge device in device tree, select Create deployment for Edge device 

8.verify the module list display repeat 

![image](https://user-images.githubusercontent.com/35018765/43816112-ba629c5c-9b05-11e8-90da-3d8fc8cd5141.png)

**Comment by konichi3** [comment] 2021-01-09 00:29
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:29 UTC
Labels: Obsolete, external dependency
