### ISSUE TITLE
Node.js module template version is not applied when another version is installed globally

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#340] opened 2019-01-08 03:35 UTC
repro on Mac/ubuntu
edge 1.8.0-rc2

steps:
1. npm i -g generator-azure-iot-edge-module
2. set the nodejs module template version in user settings.
"azure-iot-edge.version.nodemodule":"1.2.0",
"azure-iot-edge.templateInstall.nodemodule": true
3.add new module or create new solution for nodejs module
4.verify the module code is 1.3.0 
expect: 1.2.0

**Comment by LazarusX** [comment] 2019-01-08 09:10
Upstream issue: https://github.com/yeoman/yo/issues/607

Workaround:
* Uninstall the globally installed template: `npm rm -g generator-azure-iot-edge-module`

**Comment by konichi3** [comment] 2021-01-09 00:30
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:30 UTC
Labels: Obsolete, external dependency
