### ISSUE TITLE
Permission denied when run docker-compose up on Windows

### ISSUE THREAD

**Issue by shizn** [microsoft/vscode-azure-iot-edge#431] opened 2019-04-17 20:37 UTC
VS Code
Windows

Steps to Reproduce:
1. Install iotedgehubdev from VS Code notification pop up.
2. Run simulator.
3. ERROR: [Errno 13] Permission denied: 'C:\\ProgramData\\iotedgehubdev\\data\\data\\docker-compose.yml'

**Comment by jeromepeng** [comment] 2019-05-24 08:32
Encounter the same issue, please help to check it.

**Comment by marianan** [comment] 2020-09-16 22:24
@jeromepeng - could you confirm if this issue is still reproducing?

**Comment by konichi3** [comment] 2021-01-09 00:32
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:32 UTC
Labels: Obsolete, bug
