### ISSUE TITLE
Add Azure Stream Analytics Iot Edge Module in a Solution using Visual Studio Code

### ISSUE THREAD

**Issue by Ilheu** [microsoft/vscode-azure-iot-edge#504] opened 2019-10-10 10:12 UTC
Hi,
I'm trying to add an Azure Stream Analytics job in my Iot Edge Solution, using Visual Studio Code, but I keep receiving this error: "Parse Stream Analytics jobs info failed: The maximum retry count has been exceeded with empty response from the Stream Analytics."
![image](https://user-images.githubusercontent.com/8053606/66560217-d3820200-eb4e-11e9-9e75-8766aef515d9.png)

**Comment by SLdragon** [comment] 2019-10-11 07:53
Hi, @Ilheu , 
This error is because stream analytics jobs cannot response valid information after retry 3 times.
Maybe there is a network issue on your machine, or the configuration of ASA on the cloud is not correct. 
You can change your network environment or re-create an ASA and try again

**Comment by Ilheu** [comment] 2019-10-11 08:58
It is not a network problem, maybe an ASA problem! I don't know what to change in configurations ... Could it be caused by the blob storage that contains the ASA job ? 
The Diagnose says : "No health related issues found" ...
I created a new one, and I receive the same error ... 
Could it be caused by not having these fields filled ? 
![image](https://user-images.githubusercontent.com/8053606/66638883-b52f0b80-ec0d-11e9-8c82-7bb7cd009cdc.png)

**Comment by SLdragon** [comment] 2019-10-11 09:32
Hi, Ilheu, you can follow this tutorial to setup your own stream analytics jobs:
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/iot-edge/tutorial-deploy-stream-analytics.md

Make sure to associate a storage account to your ASA:

![image](https://user-images.githubusercontent.com/5545529/66641298-090d1500-ec4d-11e9-8d5a-c50754ab9845.png)

**Comment by Ilheu** [comment] 2019-10-11 09:46
Hi SLdragon ! 
I already associated my ASA to a blob storage account ... But I still cannot add my ASA module in my Solution in Visual Studio Code ...

**Comment by SLdragon** [comment] 2019-10-12 06:30
Hi, Ilheu, can you show me your other configurations? Make sure your input, output and query are corrected.

**Comment by Ilheu** [comment] 2019-10-13 13:40
Hi SLdragon ! Thanks for the quick response !

I think my inputs, outputs and queries  are correct, because I can add the ASA by Portal ... 

![image](https://user-images.githubusercontent.com/8053606/66702924-c3ac1e80-ed04-11e9-9b71-d6126eee0bd8.png)

![image](https://user-images.githubusercontent.com/8053606/66716569-1948ff80-edc7-11e9-89ab-5c52645076ed.png)

What configurations do you want ?

**Comment by SLdragon** [comment] 2019-10-22 07:03
Hi, @Ilheu, sorry for the late. 
From your screenshot, I think it is fine. Not sure what's wrong with it.

I suggest that you can follow the [tutorial]( https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-stream-analytics) and create another ASA to see whether the issue still exists. 

You can also try to [deploy the edge module on the Azure portal](https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-deploy-stream-analytics#deploy-the-job) to check whether it works fine.

If Azure portal also cannot deploy the module, I think this would be something wrong with the ASA.

**Comment by SLdragon** [comment] 2019-10-23 03:28
Hi, @llheu, from our investigation, this error is caused by the poor network or ASA process information timeout. You can retry to add an ASA module multiple times to solve the problem. 
We also plan to update the retry logic to increase the timeout and allow user to cancel it in the next release. When it's ready, we would let you know, thanks!

**Comment by nouira** [comment] 2019-10-23 20:15
I got the same problem and was resolved by trying multiple times to add the module

**Comment by SLdragon** [comment] 2019-10-25 01:23
@nouira , thanks for your feed back! This fix would be available in the next release, and I would let you know.

**Comment by Ilheu** [comment] 2019-10-28 11:49
It works in Portal, but not in Visual Studio Code ...

**Comment by SLdragon** [comment] 2019-10-29 02:47
@Ilheu , we created a pull request to fix this issue, and would be available in next release. And would let you know when it ready!
https://github.com/microsoft/vscode-azure-iot-edge/pull/505

**Comment by SLdragon** [comment] 2019-10-31 01:55
@Ilheu and @nouira , 1.18.0 has been released, and the issue should be resolved, please download the latest version and try again, thanks!

**Comment by Ilheu** [comment] 2019-10-31 09:37
@SLdragon Yes, it works ! Thank you so much !!

**Comment by adashen** [comment] 2019-11-06 01:49
Close since the issue has been fixed.

**Closed by adashen** 2019-11-06 01:49 UTC
