### ISSUE TITLE
Use the Azure extension to display the IoT Hub & the devices instead of doing it in the explorer

### ISSUE THREAD

**Issue by paloukari** [microsoft/vscode-azure-iot-edge#263] opened 2018-10-05 20:54 UTC
Have a look how the rest of the Azure VS Code extensions do this: e.g. Logic Apps

![image](https://user-images.githubusercontent.com/7554503/46559779-34c12680-c8a6-11e8-96ec-516db63639c6.png)

**Comment by konichi3** [comment] 2021-01-09 00:29
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:29 UTC
Labels: Obsolete, external dependency
