### ISSUE TITLE
[Add IoT Edge Module] The cursor will automatically move to the end of the module name

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#77] opened 2018-03-20 09:13 UTC
Right-click on deployment.template.json file, and click Add IoT Edge Module 

Follow the steps and input required fields to add a new module
the SampleModule already exist, so I want to add a Module named  FunctionSampleModule 
![image](https://user-images.githubusercontent.com/35018765/37645300-6936dbb2-2c61-11e8-9c8d-9447e4bb21e7.png)
when I input the first letter F, The cursor will automatically move to the end of the word

![image](https://user-images.githubusercontent.com/35018765/37645322-74e6d3c2-2c61-11e8-8068-f20cdfb74ed8.png)

**Comment by formulahendry** [comment] 2018-03-21 03:29
Good finding. It should be the bug of VS Code: it will always move the cursor to the end when status of input value changed from invalid to valid. @czgtest Could you help open an issue to the vscode repo? https://github.com/microsoft/vscode/issues

**Comment by czgtest** [comment] 2018-03-22 05:39
@formulahendry   when create new Edge device,  it need to input device name, but this issue is not repro on,  I don't know what's the difference.

![image](https://user-images.githubusercontent.com/35018765/37752968-9a32fc58-2dd5-11e8-90f6-3a672ee02bcc.png)

![image](https://user-images.githubusercontent.com/35018765/37753006-c9d1b10c-2dd5-11e8-8ac3-3cf19c2a2708.png)

**Comment by formulahendry** [comment] 2018-03-22 05:44
There is no input validation for `create Edge Device`

**Comment by konichi3** [comment] 2021-01-05 00:19
Hi 

We are triaging issues that are more than a few months old. 
If you don’t mind, can you follow the guidance below and take corresponding actions?

-	Please review that the issue reported still exists on the latest products (IoT Edge runtime, tooling, Visual Code/Studio extensions)
-	If it’s still an issue, please consider filing a new issue with following additional information 
o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

We plan to close issues that are more than 3 months old in a few weeks. Providing further information in a new issue ticket allow our team to triage the issue quickly.

Thank you for your feedback and interests.

Thank you,
Azure IoT Developer and Device team

**Comment by konichi3** [comment] 2021-01-09 00:28
Sorry. Please disregard the previous comment. Below is the right one

Hi

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o If you believe it’s a bug, provide detail repro steps.
o If it’s a feature request, please note as such
o Expected outcome
o Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:28 UTC
Labels: Obsolete, P2, external dependency
