### ISSUE TITLE
Consider building docker image in the cloud

### ISSUE THREAD

**Issue by lirenhe** [microsoft/vscode-azure-iot-edge#60] opened 2018-03-16 08:24 UTC
Setting Docker, downloading Docker components and creating docker image takes a lot of time in my machine.
There is no need to do that work in local if I don't want to do local testing and debugging.
Consider move that part to Azure so that I could submit code only.

**Comment by andresrinivasan** [comment] 2018-12-10 19:57
+1 for this enhancement

**Comment by shizn** [comment] 2018-12-10 20:37
@andresrinivasan thanks. This is in our roadmap. We are trying to integrate [ACR tasks](https://docs.microsoft.com/en-us/azure/container-registry/container-registry-tasks-overview) to achieve this.

**Comment by konichi3** [comment] 2021-01-05 00:17
Hi 

We are triaging issues that are more than a few months old. 
If you don’t mind, can you follow the guidance below and take corresponding actions?

-	Please review that the issue reported still exists on the latest products (IoT Edge runtime, tooling, Visual Code/Studio extensions)
-	If it’s still an issue, please consider filing a new issue with following additional information 
o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

We plan to close issues that are more than 3 months old in a few weeks. Providing further information in a new issue ticket allow our team to triage the issue quickly.

Thank you for your feedback and interests.

Thank you,
Azure IoT Developer and Device team

**Comment by konichi3** [comment] 2021-01-09 00:27
Sorry. Please disregard the previous comment. Below is the right one

Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:27 UTC
Labels: Obsolete, enhancement
