### ISSUE TITLE
Run IoT edge solution in simualtor failed in Moby engine

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#451] opened 2019-05-22 08:54 UTC
- VSCode Version: 1.33
- OS Version: Windows10
- Extension Version: 1.13.0-rc2

Steps to Reproduce:

1. Open VSCode with **admin** , because iotedge_moby only use with admin 
2. Make sure iotedge-moby service is running in windows service  and iotedge service is stopped. 
3. Configure azure-iot-edge.executor.env and add env 
"DOCKER_HOST":"npipe:////./pipe/iotedge_moby_engine" 
4. Save the env. And reload window. 
5. create new solution for C# module 
6. build and push IoT edge solution 
check the image is push in moby 
7. right click  deployment.windows-amd64.json and run edge solution in simulator
check the logs of edgeHubDev

 One or more errors occurred. (Access to the path 'c:\mnt\edgehub\edge-chain-ca.cert.pem' is denied.) ---> System.UnauthorizedAccessException: Access to the path 'c:\mnt\edgehub\edge-chain-ca.cert.pem' is denied.

![image](https://user-images.githubusercontent.com/35018765/58161072-2f3c1380-7cb2-11e9-9c1e-7353a309360c.png)

8.computer will auto restart

**Comment by adashen** [comment] 2019-05-23 01:41
Please clean your moby environment and try again

**Comment by czgtest** [comment] 2019-05-23 09:35
step:
1.docker -H "npipe:////./pipe/iotedge_moby_engine" system prune -a -f
2.docker -H "npipe:////./pipe/iotedge_moby_engine" volume prune
3.docker -H "npipe:////./pipe/iotedge_moby_engine" volume list
4.delete edgeHubDev and edgemoduledev folder in C:\ProgramData\iotedge-moby\volumes
5.iotedgehubdev start -H "npipe:////./pipe/iotedge_moby_engine"
6.docker -H  "npipe:////./pipe/iotedge_moby_engine" logs edgeHubDev
One or more errors occurred. (Access to the path 'c:\mnt\edgehub\edge-chain-ca.cert.pem' is denied.) ---> System.UnauthorizedAccessException: Access to the path 'c:\mnt\edgehub\edge-chain-ca.cert.pem' is denied.
![image](https://user-images.githubusercontent.com/35018765/58242261-10588280-7d81-11e9-8172-4d4f6346de54.png)

**Comment by czgtest** [comment] 2019-12-11 09:12
this issue will repro too.

**Comment by konichi3** [comment] 2021-01-09 00:33
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:33 UTC
Labels: Obsolete, external dependency
