### ISSUE TITLE
[C module][dockerfile.amd64]  C module send message failed

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#335] opened 2019-01-04 10:25 UTC
repro on edge 1.8.0-rc
windows10 
amd64 docker file

create new solution for c module
select amd64 platform
build and push iot edge solution for deployment.template.json
verify docker logs of c module, message is not sending

```
C:\Users\v-czg>docker logs SampleModuleC02
Waiting for incoming messages.
Error: Time:Fri Jan  4 10:14:33 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:wait_for_connection Line:386 Failure: connect failure 111.
Error: Time:Fri Jan  4 10:14:33 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:socketio_open Line:770 wait_for_connection failed
Error: Time:Fri Jan  4 10:14:33 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Fri Jan  4 10:14:33 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Fri Jan  4 10:14:33 2019 File:/build/azure-umqtt-c-M2FdAB/azure-umqtt-c-0.2.0.0/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Fri Jan  4 10:14:33 2019 File:/build/azure-iot-sdk-c-83uUq0/azure-iot-sdk-c-0.2.0.0/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2141 failure connecting to address zhangchen.
Error: Time:Fri Jan  4 10:14:37 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:wait_for_connection Line:386 Failure: connect failure 113.
Error: Time:Fri Jan  4 10:14:37 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:socketio_open Line:770 wait_for_connection failed
Error: Time:Fri Jan  4 10:14:37 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Fri Jan  4 10:14:37 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Fri Jan  4 10:14:37 2019 File:/build/azure-umqtt-c-M2FdAB/azure-umqtt-c-0.2.0.0/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Fri Jan  4 10:14:37 2019 File:/build/azure-iot-sdk-c-83uUq0/azure-iot-sdk-c-0.2.0.0/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2141 failure connecting to address zhangchen.
Error: Time:Fri Jan  4 10:14:37 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:wait_for_connection Line:386 Failure: connect failure 111.
Error: Time:Fri Jan  4 10:14:37 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:socketio_open Line:770 wait_for_connection failed
Error: Time:Fri Jan  4 10:14:37 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Fri Jan  4 10:14:37 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Fri Jan  4 10:14:37 2019 File:/build/azure-umqtt-c-M2FdAB/azure-umqtt-c-0.2.0.0/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Fri Jan  4 10:14:37 2019 File:/build/azure-iot-sdk-c-83uUq0/azure-iot-sdk-c-0.2.0.0/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2141 failure connecting to address zhangchen.
Error: Time:Fri Jan  4 10:14:41 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:wait_for_connection Line:386 Failure: connect failure 111.
Error: Time:Fri Jan  4 10:14:41 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:socketio_open Line:770 wait_for_connection failed
```

![image](https://user-images.githubusercontent.com/35018765/50683752-207bf980-104e-11e9-9278-fcb0f01124ab.png)

**Comment by czgtest** [comment] 2019-01-07 05:15
today I create a new solution for C module,  the above error will repro , then D2C message is sending , 

C:\Users\v-czg>docker logs SampleModuleC0107
Waiting for incoming messages.
Error: Time:Mon Jan  7 05:10:43 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:wait_for_connection Line:386 Failure: connect failure 111.
Error: Time:Mon Jan  7 05:10:43 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:socketio_open Line:770 wait_for_connection failed
Error: Time:Mon Jan  7 05:10:43 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Jan  7 05:10:43 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Mon Jan  7 05:10:43 2019 File:/build/azure-umqtt-c-M2FdAB/azure-umqtt-c-0.2.0.0/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Mon Jan  7 05:10:43 2019 File:/build/azure-iot-sdk-c-83uUq0/azure-iot-sdk-c-0.2.0.0/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2141 failure connecting to address zhangchen.
Error: Time:Mon Jan  7 05:10:43 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:wait_for_connection Line:386 Failure: connect failure 111.
Error: Time:Mon Jan  7 05:10:43 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:socketio_open Line:770 wait_for_connection failed
Error: Time:Mon Jan  7 05:10:43 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Jan  7 05:10:43 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Mon Jan  7 05:10:43 2019 File:/build/azure-umqtt-c-M2FdAB/azure-umqtt-c-0.2.0.0/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Mon Jan  7 05:10:43 2019 File:/build/azure-iot-sdk-c-83uUq0/azure-iot-sdk-c-0.2.0.0/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2141 failure connecting to address zhangchen.
Error: Time:Mon Jan  7 05:10:45 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:wait_for_connection Line:386 Failure: connect failure 111.
Error: Time:Mon Jan  7 05:10:45 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/socketio_berkeley.c Func:socketio_open Line:770 wait_for_connection failed
Error: Time:Mon Jan  7 05:10:45 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Mon Jan  7 05:10:45 2019 File:/build/azure-c-shared-util-mYcWJg/azure-c-shared-util-0.2.0.0/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
Error: Time:Mon Jan  7 05:10:45 2019 File:/build/azure-umqtt-c-M2FdAB/azure-umqtt-c-0.2.0.0/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
Error: Time:Mon Jan  7 05:10:45 2019 File:/build/azure-iot-sdk-c-83uUq0/azure-iot-sdk-c-0.2.0.0/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2141 failure connecting to address zhangchen.
Received Message [0]
 Data: [{"machine":{"temperature":21.967841884222739,"pressure":1.1102604678228438},"ambient":{"temperature":20.797237227809259,"humidity":25},"timeCreated":"2019-01-07T05:10:51.8227978Z"}.11%�]
Sending message (0) to the next stage in pipeline
Confirmation[0] received for message with result = 0
Received Message [1]
 Data: [{"machine":{"temperature":22.375403226295209,"pressure":1.1566915067931252},"ambient":{"temperature":21.228036979086713,"humidity":24},"timeCreated":"2019-01-07T05:10:57.0345017Z"}]
Sending message (1) to the next stage in pipeline
Confirmation[1] received for message with result = 0
Received Message [2]
 Data: [{"machine":{"temperature":22.37565773009586,"pressure":1.1567205008969967},"ambient":{"temperature":20.775874622760281,"humidity":24},"timeCreated":"2019-01-07T05:11:02.05696Z"}Z"}]
Sending message (2) to the next stage in pipeline
Confirmation[2] received for message with result = 0
Received Message [3]
 Data: [{"machine":{"temperature":22.989292828361172,"pressure":1.2266282969019058},"ambient":{"temperature":20.68726478665474,"humidity":26},"timeCreated":"2019-01-07T05:11:07.0794449Z"}]
Sending message (3) to the next stage in pipeline
Confirmation[3] received for message with result = 0
Received Message [4]
 Data: [{"machine":{"temperature":22.767030916650327,"pressure":1.2013073196183917},"ambient":{"temperature":21.462673581187929,"humidity":25},"timeCreated":"2019-01-07T05:11:12.1031336Z"}]
Sending message (4) to the next stage in pipeline
Confirmation[4] received for message with result = 0

**Comment by formulahendry** [comment] 2019-01-08 07:01
Similar issue https://github.com/Azure/azure-iot-sdk-c/issues/746, depends on C SDK

**Comment by adashen** [comment] 2019-08-29 02:14
@czgtest since the related issue is closed please check again with new c module

**Comment by czgtest** [comment] 2019-08-29 04:46
this issue also repro on ,  it will throw error in docker logs, but then D2C message will send successfully.

**Comment by czgtest** [comment] 2019-08-29 04:48
https://github.com/microsoft/vscode-azure-iot-edge/issues/335

**Comment by konichi3** [comment] 2021-01-09 00:30
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:30 UTC
Labels: Obsolete, external dependency
