### ISSUE TITLE
Build and Run IoT Edge Solution in Simulator fails on LODS VM environment

### ISSUE THREAD

**Issue by darenm** [microsoft/vscode-azure-iot-edge#556] opened 2020-08-03 20:30 UTC
- VSCode Version: 1.47.3
- OS Version: 10 2004 19041.329
- Extension Version: Azure IoT Edge v1.22.0

Steps to Reproduce:

The Lab Instructions that are being followed are documented at: https://microsoftlearning.github.io/AZ-220-Microsoft-Azure-IoT-Developer/Instructions/Labs/LAB_AK_13-deploy-and-debug-custom-azure-iot-edge-module.html#exercise-1-verify-lab-prerequisites

1. Switch to the Visual Studio Code instance containing your IoT Edge solution.

1. In the Explorer pane, right-click deployment.debug.template.json, and then click Build and Run IoT Edge Solution in Simulator.

1. When you see the prompt to setup iotedgehubdev, click Setup.

1. When prompted for the IoT Hub Connection String, enter the Connection string–primary key you noted earlier.

1. When prompted to Select an IoT Edge Device, click SimulatedDevice.

1. In the Explorer pane, right-click deployment.debug.template.json, and then click Build and Run IoT Edge Solution in Simulator.

Does this issue occur when all other extensions are disabled?: Yes

When attempting to build a custom IoT Edge c# module using the VS Code IoTEdge extension within the Learning On Demand (LODS) virtual environment, the command fails with the following error message:

Error
```
"/mnt/c/Users/Admin/.vscode/extensions/vsciot-vscode.azure-iot-edge-1.22.0/iotedgehubdev/0.14.1/iotedgehubdev" setup -c "HostName=iot-az220-training-dm20200803.azure-devices.net;DeviceId=SimulatedDevice;SharedAccessKey=<removed-key>=" -i "HostName=iot-az220-training-dm20200803.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=<removed-key>"

authority@SEA-DEV:/mnt/c/Users/Admin/Documents/EdgeSolution$ "/mnt/c/Users/Admin/.vscode/extensions/vsciot-vscode.azure-iot-edge-1.22.0/iotedgehubdev/0.14.1/iotedgehubdev" setup -c "HostName=iot-az220-training-dm20200803.azure-devices.net;DeviceId=SimulatedDevice;SharedAccessKey=<removed-key>" -i "HostName=iot-az220-training-dm20200803.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=<removed-key>"
bash: /mnt/c/Users/Admin/.vscode/extensions/vsciot-vscode.azure-iot-edge-1.22.0/iotedgehubdev/0.14.1/iotedgehubdev: No such file or directory

authority@SEA-DEV:/mnt/c/Users/Admin/Documents/EdgeSolution$
```

The LODS VM has the following installed:

* WIndows 10 2004 19041.329
* Python 3.8.5
* pip installed iotedgehubdev 1.14.1
* Docker version 19.03.12
* WSL 2 running
  * Legacy V1
  * docker-desktop-data V2
  * docker-desktop V2
* Visual Studio Code 1.47.3
  * Extensions:
     * Azure IoT Tools v0.3.0 including Azure IoT Edge v1.22.0
     * C# 1.22.1

**Comment by darenm** [comment] 2020-08-04 15:15
I executed the lab in an ExpressLabs virtual environment and the command executed OK - I noticed that in this environment the `iotedgehubdev` command is executed using PowerShell rather than bash. The environment has different versions of Python and Docker:
* Python - 3.7.6
* Docker version 19.03.5

**Comment by czgtest** [comment] 2020-08-20 07:31
In the Learning On Demand (LODS) virtual environment，the iotedgehubdev command executed failed, because it can't find the iotedgehubdev in the path ""/mnt/c/Users/Admin/.vscode/extensions/vsciot-vscode.azure-iot-edge-1.22.0/iotedgehubdev/0.14.1/iotedgehubdev""

you can use bellow command to run the solution :

1. install simulator tool
authority@SEA-DEV:/mnt/c/Users/Admin/Documents/EdgeSolution$pip install iotedgehubdev
2.setup connection string
authority@SEA-DEV:/mnt/c/Users/Admin/Documents/EdgeSolution$iotedgehubdev setup -c "device connection string"
3. run the solution
authority@SEA-DEV:/mnt/c/Users/Admin/Documents/EdgeSolution$iiotedgehubdev run confg/deployment.debug.amd64.json
4.stop the simulator
iotedgehubdev stop

**Comment by SLdragon** [comment] 2020-08-20 09:13
Hi, @darenm, sorry for the late, from your errors, it indicate that the vscode cannot find iotedgehubdev binaries in the path: 

```
/mnt/c/Users/Admin/.vscode/extensions/vsciot-vscode.azure-iot-edge-1.22.0/iotedgehubdev/0.14.1/iotedgehubdev
```

the path in your bash is not a normal windows path, it seems like a linux path. I am not familar with the LODS virtual environment, so maybe you can try the steps czgtest metioned to check whether it can solve the problem.


If there are some problems integrite with the VSCode, you can try to use edge extension 1.18, which by default use the pip version of the iotedgehubdev

**Comment by darenm** [comment] 2020-08-20 15:17
That's really the point of me raising the issue - it appears that the configuration of the [LODS environment](https://tsfb.learnondemand.net/) is revealing a bug in the Extension that is incorrectly launching Windows bash and using an invalid path, whereas in other environments, it uses the correct version. 
I will see if using the 1.18 version of the edge extension is successful - however, as you know, installing the Azure IoT Tools package automatically installs the latest.

**Comment by konichi3** [comment] 2021-01-09 00:34
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:34 UTC
Labels: Obsolete
