### ISSUE TITLE
Save History of Direct method calls - Name and Payload both

### ISSUE THREAD

**Issue by avkewalr-msft** [microsoft/vscode-azure-iot-edge#549] opened 2020-05-25 15:57 UTC
Would be great to have a saved history of **Direct method calls on modules** via Invoke Modules Direct Method in VS code. 

https://github.com/Microsoft/vscode-azure-iot-toolkit/wiki/Invoke-Device-Direct-Method

Should save history of call method name and your last submitted payload associated with that method call.  

Should be contextual to the user. However, I will leave it up to you to decide if it should be context aware of particular module. e.g. module 1 has history list 1 and module 2 has history list 2 or both modules can see history list 1 and 2. I think it should be contextual to module as every module has different direct methods.

Scenario is we have a list of methods our customers are going to be calling from VS Code on our module and it is repetitive and time wasting to keep going to another doc to fetch the payload every time the customer goes back to an to an older call made 5 mins back.

e.g. as per link above, let's assume if the method call was on module 1

1. Call SetTelemetryEvent with payload 1
2. Call SetXXX with **large** payload 2
3. Call SetTelemetryEvent with payload 1
4. Call SetYYY with **large** payload 3
**5. Call SetXXX with **large** payload 2**

5 repeats 2, history would be good rather than typing name and payload.

Same issue might be face in **direct methods on devices** rather than module, although our scenario is module specific.

**Comment by SLdragon** [comment] 2020-05-26 06:01
Hi, @avkewalr-msft , thank you for your suggestions, and this is a feature request and please stay tuned for the updates.

**Comment by konichi3** [comment] 2021-01-09 00:33
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:33 UTC
Labels: Obsolete, feature request
