### ISSUE TITLE
[Config the version settings]If the image values of edgeHub/edgeAgent/tempSensor are invalid, there should be an error or reminder 

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#311] opened 2018-12-04 09:36 UTC
Repro on edge 1.7.0-rc

Steps:
Open user settings 
set the version of edgeHub/edgeAgent/tempSensor images .

if the image values are invalid ,  there is not any reminder for user,  maybe user can find this invalid when build and push IoT edge solution in error logs,   but this is not friendly user experience. can we improve it?

![image](https://user-images.githubusercontent.com/35018765/49432436-a48e5780-f7ea-11e8-819b-2debd85d1123.png)

**Comment by konichi3** [comment] 2021-01-09 00:30
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:30 UTC
Labels: Obsolete, enhancement
