### ISSUE TITLE
Cannot add dotnet template for C# module when have private nuget feed

### ISSUE THREAD

**Issue by shizn** [microsoft/vscode-azure-iot-edge#437] opened 2019-05-03 22:33 UTC
- VSCode Version: Any
- OS Version: Any
- Extension Version: Windows 10

Steps to Reproduce:

1. Open CMD of PS
2. `nuget sources add -Name IoT-PnP -Source "<please ask @shizn for this feed>"`
3. `dotnet new -i Microsoft.Azure.IoT.Edge.Module`

![image](https://user-images.githubusercontent.com/3619378/57168906-cc451400-6db8-11e9-9db1-e006f6358a50.png)

Does this issue occur when all other extensions are disabled?: Yes

**Comment by shizn** [comment] 2019-05-03 22:44
Should we force the command to `dotnet new -i Microsoft.Azure.IoT.Edge.Module --nuget-source https://api.nuget.org/v3/index.json` ?

**Comment by adashen** [comment] 2019-05-13 07:57
@shizn Can you check your nuget configuration file at %appdata%\NuGet\NuGet.Config whether https://api.nuget.org/v3/index.json is set as source there. 

The source is by default set. Can you give more context about the scenario that user will remove this source in the configuration?

**Comment by adashen** [comment] 2019-05-14 08:34
related issue https://github.com/NuGet/Home/issues/6140

**Comment by konichi3** [comment] 2021-01-09 00:32
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:32 UTC
Labels: Obsolete, external dependency
