### ISSUE TITLE
Failed to execute script pyi_rth_pkgres

### ISSUE THREAD

**Issue by grtn316** [microsoft/vscode-azure-iot-edge#564] opened 2020-10-17 21:09 UTC
- VSCode Version: 1.50.1
- OS Version: Win10 Latest
- Extension Version: 1.23.0

Steps to Reproduce:

1. My VSCode updated and now I am getting during build and run of my module:

Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 11, in <module>
  File "d:\a\1\s\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\pkg_resources\__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[12752] Failed to execute script pyi_rth_pkgres

I have reinstalled python, reinstalled the extension, downgraded the extension, tried to upgrade setuptools. I have using the latest version of python and pip.

Does this issue occur when all other extensions are disabled?: Yes

**Comment by lgcanto** [comment] 2020-10-23 17:21
@grtn316 I only could make it to work again by uninstalling all extensions, uninstalling VS Code and then reinstalling it all again with the most recent release

**Comment by marianan** [comment] 2020-11-03 00:16
The root cause was resolved in version 0.14.3 of iotedgehubdev https://github.com/Azure/iotedgehubdev/issues/288. If you are still experiencing the same symptoms, please update this thread.

**Comment by konichi3** [comment] 2020-11-09 22:10
Closing the issue for now

**Closed by konichi3** 2020-11-09 22:10 UTC
