### ISSUE TITLE
[delete IoT Edge Module ] not support delete IoT Edge Module

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#80] opened 2018-03-21 00:49 UTC
if user want to delete an Edge Module in solution, after click delete, the deployment.template.json/launch.json   file is not updated.

![image](https://user-images.githubusercontent.com/35018765/37690108-037104fa-2ce4-11e8-9fa7-863c37244de8.png)

![image](https://user-images.githubusercontent.com/35018765/37690268-c9f8f0b0-2ce4-11e8-96bc-87a49816c7bb.png)

**Comment by konichi3** [comment] 2021-01-05 00:20
Hi 

We are triaging issues that are more than a few months old. 
If you don’t mind, can you follow the guidance below and take corresponding actions?

-	Please review that the issue reported still exists on the latest products (IoT Edge runtime, tooling, Visual Code/Studio extensions)
-	If it’s still an issue, please consider filing a new issue with following additional information 
o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

We plan to close issues that are more than 3 months old in a few weeks. Providing further information in a new issue ticket allow our team to triage the issue quickly.

Thank you for your feedback and interests.

Thank you,
Azure IoT Developer and Device team

**Comment by konichi3** [comment] 2021-01-09 00:28
Sorry. Please disregard the previous comment. Below is the right one

Hi

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o If you believe it’s a bug, provide detail repro steps.
o If it’s a feature request, please note as such
o Expected outcome
o Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:28 UTC
Labels: Obsolete, P2, enhancement
