### ISSUE TITLE
"Entry not found in cache" error when importing ACR, ASA, and AML modules

### ISSUE THREAD

**Issue by LazarusX** [microsoft/vscode-azure-iot-edge#161] opened 2018-05-24 02:25 UTC
Reported by @czgtest 

Steps to reproduce:
1. Open VS Code for several hours without using it
2. Import an existing module on ACR
3. Notice below error:
![Screenshot](https://user-images.githubusercontent.com/716650/40461150-8ead8090-5f3c-11e8-9e0d-2bb04f94047d.png)

**Comment by LazarusX** [comment] 2018-05-24 02:50
Possibly related to https://github.com/Microsoft/vscode-azure-account/issues/53

**Comment by LazarusX** [comment] 2018-11-23 05:31
Importing ASA and AML modules is also impacted.

**Comment by adashen** [comment] 2019-12-12 02:43
microsoft/vscode-azure-account#53 external dependency

**Comment by konichi3** [comment] 2021-01-09 00:27
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:27 UTC
Labels: Obsolete, bug, external dependency
