### ISSUE TITLE
[Config the version settings] Create deployment for single device not work when swith to defferent version.

### ISSUE THREAD

**Issue by czgtest** [microsoft/vscode-azure-iot-edge#318] opened 2018-12-06 07:52 UTC
steps:
1. set the version config in user settings:
          "azure-iot-edge.version.edgeAgent": "1.0.2",
           "azure-iot-edge.version.edgeHub": "1.0.2",
           "azure-iot-edge.version.tempSensor": "1.0.2",
2.create new solution for c# function module
3.build and pull IoT edge solution
4.create deployment for single device
  it work well on edge runtime,  message is sending

5.update the version config in user settings 
"azure-iot-edge.version.edgeAgent": "1.0.4",
"azure-iot-edge.version.edgeHub": "1.0.4",
"azure-iot-edge.version.tempSensor": "1.0.4",
6.create new solution for c# module
7.build and pull  for amd64 image , then create deployment for single device 

 use  docker PS and verify the versions for edgeAgent /edgeHub
it is 1.02,but expected: 1.0.4

create deployment for single device is not working

8. manually reStart-Service iotedge
9. create deployment for single device again 
verify the docker version is changing, everything work well

10, build and pull for amd64.debug image 
11.  create deployment for single device 
here this function is not work again,  still display amd64 docker logs

![image](https://user-images.githubusercontent.com/35018765/49569420-dfb99380-f96e-11e8-86f3-28d79ba7d3c1.png)

**Comment by adashen** [comment] 2018-12-06 08:14
This is a runtime issue. The updated configuration is already deployed. mark as external dependency

**Comment by konichi3** [comment] 2021-01-09 00:30
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:30 UTC
Labels: Obsolete, external dependency
