### ISSUE TITLE
Set Module Credentials to User Settings fails

### ISSUE THREAD

**Issue by dtjensen** [Microsoft/vscode-azure-iot-edge#316] opened 2018-12-05 22:00 UTC
When testing in single module mode, the command does not correctly configure the module name, by using the -m option.  It runs "iotedgehubdev modulecred -l -o <outputfilename>", which sets the ModuleId property to "target".  The ModuleId value needs to be set to the name of the module you are testing.  This is similar to the following closed issue:

https://github.com/Microsoft/vscode-azure-iot-edge/issues/262

**Comment by adashen** [comment] 2018-12-06 03:36
@dtjensen , currently in single module mode. The module to be tested is always hard code to "target" module. And the credential is all setup for you with       "env": {
        "EdgeHubConnectionString": "${config:azure-iot-edge.EdgeHubConnectionString}",
        "EdgeModuleCACertificateFile": "${config:azure-iot-edge.EdgeModuleCACertificateFile}"
      } by VS Code.

And you could feed the message to module with rest api to an input module. Can I know your scenario, why "target" module ID failed to work for you in single module scenario?

**Comment by adashen** [comment] 2018-12-06 04:32
@dtjensen Thanks for the feedback. Since the issue cannot be reproduced. I close it for now, feel free to open if you still meet with issues.

**Closed by adashen** 2018-12-06 04:32 UTC
