### ISSUE TITLE
Issue with getting monitoring output from Azure Iot Hub VSCode extension

### ISSUE THREAD

**Issue by naiteeks** [microsoft/vscode-azure-iot-edge#558] opened 2020-09-04 17:32 UTC
- VSCode Version: Version: 1.48.2 (user setup)
- OS Version: Windows_NT x64 10.0.19041
- Extension Version: 2.16.3

Steps to Reproduce:

Launch Auzre IoT Hub VSCode extension
Set connection string ( I used: HostName=xxxxx.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=***)
Start monitoring Built In event endpoint.
See the messages in the OUTPUT window

Does this issue occur when all other extensions are disabled?: Yes/No

**Comment by adashen** [comment] 2020-09-07 02:00
@SLdragon Please help to have a look at this issue.

**Comment by SLdragon** [comment] 2020-09-07 05:45
Hi, @naiteeks , can you give some detailed information about your issues?

**Comment by SLdragon** [comment] 2020-09-07 06:51
Seems like you mentioned this issue: https://github.com/microsoft/vscode-azure-iot-toolkit/issues/491

From their latest release, this issue has been fixed in v2.16.4

**Comment by marianan** [comment] 2020-09-16 22:01
Closing as root cause has been resolved per https://github.com/microsoft/vscode-azure-iot-toolkit/issues/491 . Please reactivate the issue if the symptoms persist.

**Closed by marianan** 2020-09-16 22:01 UTC
