### ISSUE TITLE
Docker commands in PowerShell

### ISSUE THREAD

**Issue by shizn** [microsoft/vscode-azure-iot-edge#351] opened 2019-01-24 00:50 UTC
From David R. Williamson,
I'm running into a new issue with "Build and Push IoT Edge Solution" command in VS Code
It yields an error:
 
At line:1 char:235
+ ... ce\IoTEdgeAndMlSample\EdgeSolution\modules\turbofanRouter" && docker  ...

The token '&&' is not a valid statement separator in this version.
At line:1 char:308
+ ...  turbofanacrlihxmkbo.azurecr.io/turbofanrouter:0.0.1-amd64 && docker  ...

The token '&&' is not a valid statement separator in this version.
At line:1 char:545
+ ... ce\IoTEdgeAndMlSample\EdgeSolution\modules\avroFileWriter" && docker  ...

The token '&&' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine

&& isn't valid for separating commands in power shell. Instead it should be a semicolon.

**Comment by adashen** [comment] 2019-01-24 05:48
@formulahendry Do you think it would be better to always call the terminal.integrated.shell.windows value before we run command in terminal?

**Comment by formulahendry** [comment] 2019-01-24 07:16
Currently, we always call the terminal.integrated.shell.windows value before we run command in terminal. I guess the user's scenario is: At first, his terminal is powershell , then he run Edge command, then he change powershell to cmd for terminal.integrated.shell.windows, then run Edge command again.  Just `terminal.integrated.shellArgs`, it would not take effect until user reload. For this case, I think there is no need to have extra special support.

**Comment by drwill-ms** [comment] 2019-02-11 20:11
VSCode prompted me to change the terminal. I just accepted its recommendation.

I was running in an Azure VM, btw.

**Comment by drwill-ms** [comment] 2019-02-11 20:30
#AzureIoTE2E

**Comment by formulahendry** [comment] 2019-12-12 02:46
We may want to cache the terminal type (whether it is CMD or PowerShell) in https://github.com/Microsoft/vscode-azure-iot-edge/blob/master/src/common/executor.ts#L11

**Comment by konichi3** [comment] 2021-01-09 00:31
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:31 UTC
Labels: Obsolete, bug
