### ISSUE TITLE
Login to docker for me before building a module

### ISSUE THREAD

**Issue by drwill-ms** [microsoft/vscode-azure-iot-edge#439] opened 2019-05-11 00:57 UTC
After I create an Edge solution and module, and then build it, it will fail on me. The error I get is:
  > PS C:\code\e2e\Peabody> docker build  --rm -f "c:\code\e2e\Peabody\WebStream\modules\webstreamModule\Dockerfile.amd64" -t drwedgecr.azurecr.io/webstreammodule:0.0.1-amd64 "c:\code\e2e\Peabody\WebStream\modules\webstreamModule"
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.39/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile.amd64&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&session=01no47f5l88tqx60w6lubbj3c&shmsize=0&t=drwedgecr.azurecr.io%2Fwebstreammodule%3A0.0.1-amd64&target=&ulimits=null&version=1: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

I often forget to login to docker. You already have my container registry info, so why can't VS Code log in for me, or at least prompt me that it needs to login with the info I've provided?

Also, why do I need to be logged into docker just to build (not push)?

I'm running the following relevant extensions:

- Azure IoT Device Workbench 0.9.8
- Azure IoT Edge 1.12.0
- Azure Iot Hub Toolkit 2.6.0
- Azure IoT Tools 0.0.2

**Comment by drwill-ms** [comment] 2019-05-11 00:57
#AzureIoTE2E

**Comment by adashen** [comment] 2019-05-13 02:02
@drwill-ms Thanks for reporting the issue. From the log you provided. It seems the error is not related to login. Instead it seems docker daemon is not running. 
**open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.**

So can you try to check the daemon status and try again? And if it is just for build, no docker credential is needed.

**Comment by drwill-ms** [comment] 2019-05-14 15:40
Once I started docker desktop, it started working.

Can we improve the error message to more clearly state that Docker isn't running, and it is required? The statements in error message above about not being able to find a specified file and the docker client might need to be elevated to connect are misleading. One might even make a case for automatically starting docker desktop if it is not running.

**Comment by adashen** [comment] 2019-12-11 07:38
Now we adding docker running status when activating the extension.

**Comment by drwill-ms** [comment] 2019-12-11 16:23
I have noticed this change. My only feedback would be that the event chosen (when activating the extension) makes VS Code noisier than it needs to be when I start VS Code. I start it for many reasons, for many occasions when I'm not working with IoT Edge.

I'd rather only be notified when I'm building an IoT Edge project. Can that be changed?

Thanks

**Comment by adashen** [comment] 2019-12-12 02:13
@drwill-ms Thanks for the feedback. Besides build image there are lots of other commands in the extension needs docker setting up, besides we think to use the extension docker is a pre-requisite. Checking the docker status before each related command cost an extra check. So it's a balanced solution we decided. I agree from user perspective you would like to just check before you are running docker related command. So we would like to mark it as an P2 enhancement.

**Comment by drwill-ms** [comment] 2019-12-18 23:38
That's right. I think it is reasonable to expect an extension that I have installed, but am not using in each instance I launch, shouldn't be noisy. It detracts from VSCode as a nice editor for lots of uses. Honestly, it got so annoying, I resorted to disabling this extension.

**Comment by konichi3** [comment] 2021-01-09 00:32
Hi 

Thank you for filing the issue.

We are looking to clean up the reported issues that are obsolete such that our team can focus on the latest issues reported.
As such, we are going to close the issue for now.

If the issue is still blocking or critical to you, please file a new issue and we will do our best to respond as soon as possible.
When you file a new issue, please ensure following additional information are provided.

o	If you believe it’s a bug, provide detail repro steps. 
o	If it’s a feature request, please note as such
o	Expected outcome
o	Is this a blocking issue?

Thank you,
Azure IoT Developer and Device team

**Closed by konichi3** 2021-01-09 00:32 UTC
Labels: Obsolete, P2, enhancement
